export { default as LogoIcon } from "./logo";
export { default as HomeIcon } from "./home";
export { default as TransferIcon } from "./transfer";
export { default as UserIcon } from "./user";
export { default as InvestmentIcon } from "./investment";
export { default as CardIcon } from "./card";
export { default as LoanIcon } from "./loan";
export { default as ServiceIcon } from "./service-icon";
export { default as Settingsicon } from "./settings-icon";
